# Generated by Django 3.2.3 on 2021-06-17 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VegTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=10)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Veg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('slug', models.SlugField()),
                ('quantity', models.IntegerField()),
                ('note', models.TextField()),
                ('vegtypes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veg_market.vegtypes')),
            ],
        ),
    ]
