# Generated by Django 3.2.3 on 2021-06-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veg_market', '0002_auto_20210617_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
