# Generated by Django 3.2.3 on 2021-07-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veg_market', '0003_food_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=10, unique=True)),
                ('slug', models.SlugField()),
                ('item_quantity', models.IntegerField()),
            ],
        ),
    ]
