# Generated by Django 3.2.3 on 2021-07-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veg_market', '0004_shoppingcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='item_name',
            field=models.CharField(max_length=10),
        ),
    ]
